dist: xenial
language: node_js
node_js: '10.16'
stages:
  - test
jobs:
  include:
    - stage: test
      name: test:mocha
      script: npm run test
      cache: npm
      services:
        - mongodb
