dist: xenial
language: node_js
node_js: '10.16'
branches:
  only:
    - develop
    - master
    - /^greenkeeper/.*$/
    - /^(?i:release|hotfix).*$/
stages:
  - test
jobs:
  include:
    - stage: test
      name: test:mocha
      script: npm run test
      cache: npm
      services:
        - mongodb
